feat/JWT-3359_upgrate_to_gwt_2.9.0
levigo/jwt-getting-started pull request #9
Opened 2021-01-21 15:19 UTC by benjaminalbanese

2021-01-21 15:21 UTC, benjaminalbanese commented
All tutorials are working so far, even the spring boot 001 tutorial which has now java 11 elements for demonstration purposes. Only the gatling tests should still be updated to be compatible to the new JWT version

2021-01-21 17:29 UTC, benjaminalbanese commented
With the last commit the gatling tests were fixed as well. The only remaining part is now, like written earlier, upgrading to the next stable jadice web toolkit version once that is officially published. 

p.s. : we might also want to update https://levigo.de/info/display/JKB/1+-+Szenario%3A+Grundlagen as there are 2 urls mentioned, that are hopelessly outdated and will be outdated again once the code is changed. Maybe add a warning mentioning this?

2021-01-22 13:03 UTC, hoffmadd requested changes

2021-01-22 13:03 UTC, hoffmadd commented on jwt-tutorial-spring-boot-001/pom.xml
> +    <!-- The following two dependencies are not needed for this tutorial,	but were needed at a point in the real
Consider removing the dependencies then, if they are not needed. We probably do not want to confuse the Getting started user with stuff which is not needed.
However, maybe we can add a Knowledgebase Article for the case where this compatibility fix was used / needed.

2021-01-22 13:03 UTC, hoffmadd commented on jwt-tutorial-spring-boot-001/src/main/java/org/jwt/server/dataprovider/UrlDocumentDataProvider.java
> +		// use a java 10 feature: type inference
Tschakaa ;-)

2021-01-22 13:36 UTC, benjaminalbanese commented on jwt-tutorial-spring-boot-001/pom.xml
> +    <!-- The following two dependencies are not needed for this tutorial,	but were needed at a point in the real
checked again and we don't need them here even after upgrading to java 11 in the dockerfile, so i removed them.

2021-01-22 13:37 UTC, hoffmadd commented on jwt-tutorial-spring-boot-001/pom.xml
> +    <!-- The following two dependencies are not needed for this tutorial,	but were needed at a point in the real
+1

2021-01-22 15:28 UTC, Crow08 commented
in `Application.gwt.xml` is 
`<!DOCTYPE module PUBLIC "-//Google Inc.//DTD Google Web Toolkit 2.8.0//EN" "http://www.gwtproject.org/doctype/2.8.2/gwt-module.dtd">` defined. Is there a 2.9 dtd?

2021-01-22 15:44 UTC, Crow08 commented
The normal tutorials work as intended but the Spring tutorial always returns 404 without throwing an error...
Is this a problem on my end only?

2021-01-28 23:34 UTC, benjaminalbanese commented
> in `Application.gwt.xml` is
> `<!DOCTYPE module PUBLIC "-//Google Inc.//DTD Google Web Toolkit 2.8.0//EN" "http://www.gwtproject.org/doctype/2.8.2/gwt-module.dtd">` defined. Is there a 2.9 dtd?

I searched for a new definition some months ago after gwt 2.9.0 was released, but i did not find anything, including within the gwt source code.

2021-01-28 23:43 UTC, benjaminalbanese commented
> The normal tutorials work as intended but the Spring tutorial always returns 404 without throwing an error...
> Is this a problem on my end only?

I built the whole project again with jdk 11 after upgrading the jadice web toolkit version, and in a second run i built the spring-boot-000 project again with jdk 8. ( the 001 project aims at showing java 11 compatibility, so you can't built it with jdk 8)

In all scenarios i didn't hava a problem, the documets loaded as intended. Could you please build the project again after getting the latest commit from some hours ago and check again if the error occurs?

2021-01-29 16:21 UTC, Crow08 approved these changes

2021-01-29 16:27 UTC, hoffmadd approved these changes

2021-01-29 16:29 UTC, merged